version: 2.1

jobs:


  test-and-document:
    macos:
      xcode: 13.3.0

    steps:
      - checkout
      - run: swift test -v



  test:
    macos: 
      xcode: 13.3.0

    steps:
      - checkout
      - run: swift test -v
      - run: .circleci/generate-documentation.sh



workflows:
  "Tests": 
    jobs:
      - test-and-document:
          filters:
            branches:
              only: 
                - main

  "Pull Request Tests": 
    jobs:
      - test:
          filters:
            branches:
              ignore: 
                - main

