version: 2.1

jobs:


  test-and-document:
    macos:
      xcode: 13.3.0

    steps:
      - checkout
      - run: swift test -v



  test:
    macos: 
      xcode: 13.3.0

    steps:
      - checkout
      - run: 
          name: Run unit tests
          command: swift test -v
      - run: 
          name: Generate Documentation 
          command: |
                    mkdir -p "docs"
                    swift package \
                        --allow-writing-to-directory "docs" \
                        generate-documentation \
                        --target HatchParser \
                        --disable-indexing \
                        --transform-for-static-hosting \
                        --hosting-base-path "Hatch/docs" \
                        --output-path "docs"
                    ls -laR
                    printenv
                    
      - run:
            name: Install dependencies
            command: |
                    npm install -g --silent gh-pages@2.0.1
                    git config user.email "ci@circleci.com"
                    git config user.name "ci"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist docs


workflows:
  "Tests": 
    jobs:
      - test-and-document:
          filters:
            branches:
              only: 
                - main

  "Pull Request Tests": 
    jobs:
      - test:
          filters:
            branches:
              ignore: 
                - main

