name: Tests

on:
  push:
    branches: [ main ]

jobs:
  buildAndTest:
    name: Build & Test
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v
