name: Test Gen Doc

on:
  push:
    branches-ignore: [ 'gh-pages' ]

  workflow_dispatch:

jobs:
  createDocs:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      
      - name: Run script
        run: ./.github/scripts/doc-gen.sh
      
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
