name: Test Gen Doc

on:
  push:
    branches-ignore: [ 'gh-pages' ]

  workflow_dispatch:

jobs:
  createDocs:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      
      - name: Run script
        run: ./.github/scripts/doc-gen.sh
      
      - uses: seanmiddleditch/gha-publish-to-git@master
        with:
          branch: gh-pages
          github_token: '${{ secrets.GITHUB_TOKEN  }}'
          github_pat: '${{ secrets.GH_PAT }}'
          source_folder: docs
          
